### ISSUE TITLE
running honeymap with hpfeeds -- possible?

### ISSUE THREAD

**Issue by honeymap** [hpfeeds/hpfeeds#23]
Mark (and/or community at large):

Has anyone tried to running honeymap with hpfeeds, instead of using hpfriends?  

I initially thought that hpfriends was built off of hpfeeds, but after speaking to Flo @ honeymap, that doesn't sound to be the case. 

From the way Flo responded here (https://github.com/fw42/honeymap/issues/9),  it makes me think that it might be remotely possible.

**Comment by Jc2k** [comment]
Hi - just closing down some old tickets from before I joined the team. Sorry for the noise.
