### ISSUE TITLE
Broker seems not to release memory

### ISSUE THREAD

**Issue by abes975** [hpfeeds/hpfeeds#29]
It seems that broker is not releasing memory after heavy load of feeds.
Broker memory is growing under heavy load of published feeds and it' s not released after the heavy load is over.
(reached more than 12G of used ram)
It seems that python garbage collector is not running (maybe due to object ref count that is not zero?? (just an hypothesis) )
Using python 2.7.3 on ubuntu linux (kernel 3.2.0.29)

**Comment by Jc2k** [comment]
Hi - just closing down some old tickets from before I joined the team. Sorry that this ticket wasn't picked up at the time.

The broker this ticket is about is no longer maintained - it has been replaced by a python 3 asyncio port.
