### ISSUE TITLE
Channel sharing

### ISSUE THREAD

**Issue by zam89** [hpfeeds/hpfeeds#32]
Hi,

I want to ask. It is possible to share channel between two different keys?
I'm still looking method to share channel similar like hpfriends.

Thanks.

**Comment by Jc2k** [comment]
Hi - just closing down some old tickets from before I joined the team. Sorry that this ticket wasn't picked up at the time.

For the record, if i understand what you mean correctly then yes - any channel can have any number of publish only or subscribe only or publish and subscribe keys associated with it.
