### ISSUE TITLE
Time stamp in mhn 

### ISSUE THREAD

**Issue by puneetbrar** [hpfeeds/hpfeeds#34]
Dear All

We are having issues with the time stamp we want to change the time stamp from utc to local or gmt 
can anybody tell us how can we do that 

the value in Modern honeypot network is coming -5.30 of the local system time 

Regards
Puneet Brar

**Comment by Jc2k** [comment]
Hi - just closing down some old tickets from before I joined the team. Sorry that this ticket wasn't picked up at the time.

If you do still need help with hpfeeds let us know, but I can't help you with MHN unfortunately.
