### ISSUE TITLE
new() swallows sleepwait parameter

### ISSUE THREAD

**Issue by srenfo** [hpfeeds/hpfeeds#39]
`hpfeeds.py`: `new` swallows `sleepwait`

Submitting this as an issue rather than as a patch because it almost looks intentional what with the `certfile=certfile` business in the `HPC_SSL` line.

If it's not intentional then I suggest the defaults of `__init__` be removed in addition to the fix.

**Comment by Jc2k** [comment]
Hi - just closing down some old tickets from before I joined the team. Sorry that this ticket wasn't picked up at the time.

The current code passes any left over kwargs from `new()` into both classes which i think fixes this.
