### ISSUE TITLE
How to use HPFeeds?

### ISSUE THREAD

**Issue by riupie** [hpfeeds/hpfeeds#44]
I wanna implement this hpfeeds protocol on my Dionaea sensor. What should I do? because I cant find any reference about it. All I found are only implementation with MHN. :(

**Comment by Jc2k** [comment]
Hi - just closing down some old tickets from before I joined the team. Sorry that this ticket wasn't picked up at the time. I'm guessing that you either solved this problem or did something else instead.

If you still want to run hpfeeds, there is documentation for the new version [here](https://python.hpfeeds.org/en/latest/broker.html). There is native support in Dionaea for hpfeeds, and an example yaml config is [here](https://github.com/DinoTools/dionaea/blob/90b8467af9962cb08f9b766bc72165554ee83e13/conf/ihandlers/hpfeeds.yaml).
