### ISSUE TITLE
hpfeed

### ISSUE THREAD

**Issue by sikhan555** [hpfeeds/hpfeeds#45]
Hi,
I required some information regarding hpfeeds, there is any option where we can send hpfeeds to several server, which deploy multiple location so we can integrate that hpfeeds.

I have two location for test base, where i want to do one hpfeeds to another server live. which may help me to analyze and further research work. 

Kindly advice.

**Comment by spitfire-sidra** [comment]
Maybe you can use [hpfeeds-client](https://github.com/rep/hpfeeds/tree/master/cli) to subscribe a channel?

**Comment by sikhan555** [comment]
Thanks for ur reply.
Can you guide me how to do this.
I am new and know just basic.

Thanks in advanced


Regards

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
