### ISSUE TITLE
https ssl enable on port 10000

### ISSUE THREAD

**Issue by dipenpatel235** [hpfeeds/hpfeeds#46]
Hello..
i have did below change in `broker/feedbroker.py` file. related https cert.

`from evnet import listenssl
.
.
        self.listener = listenssl(host=FBIP, port=FBPORT, cert ='localhost.crt')
`
now i have not getting idea what change i do from `hpfeed.py` client side code to communicate with ssl cert.

**Comment by Jc2k** [comment]
Hi - just closing down some old tickets from before I joined the team. Sorry that this ticket wasn't picked up at the time.

The broker this ticket is about is no longer maintained - it has been replaced by a python 3 asyncio port. The evenet broker was deleted in June 2014.
