### ISSUE TITLE
Update hpfeeds.org for Go implementation

### ISSUE THREAD

**Issue by d1str0** [hpfeeds/hpfeeds#49]
Sorry if this is the wrong spot for issues related to the hpfeeds.org site.

The current hpfeeds/go-hpfeeds repo is quite out of date. [d1str0/hpfeeds](https://github.com/d1str0/hpfeeds) is refactored and expanded. This includes a working Broker implementation.

This library is currently in use by Anomali (formerly ThreatStream, owner of [MHN](https://github.com/threatstream/mhn)) as well as several other modern honeypots such as [drupot](https://github.com/d1str0/drupot) and [magenpot](https://github.com/trevorleake/magenpot)

I'm the current maintainer of MHN and am also actively developing new honeypots using Go and hpfeeds.

**Comment by Jc2k** [comment]
Hey @d1str0 - thanks for reaching out. The source for the website (and issue tracker for it) is [here](https://github.com/hpfeeds/hpfeeds.github.io).

I'm not a go user myself but I saw that you raised a PR against the "upstream" go library. I hope thats something that we can get merged soon. In the meantime i'd happily link to both libraries from the site. I'm away from civilization right now, but if you sent a PR I could probably merge it on my phone.

Incidentally, do you guys control https://pypi.org/project/hpfeeds/? I've got a biggish release of the python library nearly ready to go but found out @rep doesn't "own" the pypi project. Is that something you can help with?

**Comment by Jc2k** [comment]
I've poked about your pull request but in the meantime i've added your library and broker to hpfeeds.org.

**Comment by Jc2k** [comment]
Closing this because the website change was done.
