### ISSUE TITLE
Error when importing hpfeeds module

### ISSUE THREAD

**Issue by Moooser** [hpfeeds/hpfeeds#52]
when trying to import hpfeeds with python3 a syntax error is shown:

File "~/.local/lib/python3.6/site-packages/hpfeeds.py", line 114
    except socket.error, e:
                       ^
SyntaxError: invalid syntax

Thanks in advance.

**Comment by Jc2k** [comment]
At a guess you installed hpfeeds from pypi. Unfortunately another org (not the hpfeeds team) controls that. And it’s not a python 3 compatible version!

Haven’t had time to chase them about giving us access, for now you can use the hpfeeds3 package or install from git.

**Comment by Jc2k** [comment]
I've not heard anything about how you got on with this, so i'm going to assume this helped? There is another ticket for tracking when we can do a new release so im going to close this one now. Do ping me if you are still having trouble!
