### ISSUE TITLE
Release new pypi build

### ISSUE THREAD

**Issue by Jc2k** [hpfeeds/hpfeeds#54]
Currently the `hpfeeds` package on pypi is not controlled by the hpfeeds maintainers. That means we can't do a release of the python 3 support, asyncio client or twisted client. We would like to track down the kind soul who uploaded 'hpfeeds 1.0' for us so that we can release '2.0'.

The `hpfeeds` package was uploaded by threatstream and they had a fork of hpfeeds at [https://github.com/threatstream/hpfeeds](https://github.com/threatstream/hpfeeds). This now redirects to [https://github.com/pwnlandia/hpfeeds](https://github.com/pwnlandia/hpfeeds).

It looks like @d1str0 has committed to there this year. @d1str0 are you able to help us resolve this?

**Comment by d1str0** [comment]
I'm talking with them now to see if they can add me and others as a maintainer for that project.

**Comment by d1str0** [comment]
They shifted all other hpfeeds/mhn related repos etc. over to me, but the pypi slipped through the cracks. Should be able to get access, but not sure how quickly.

**Comment by Jc2k** [comment]
Awesome! Thanks for looking into it!

**Comment by d1str0** [comment]
@Jc2k who should be considered maintainers for the pypi repo? If you have a twitter, can you PM me some deets? Or is there a better way to share info?

**Comment by Jc2k** [comment]
Sorry for the delay getting back to you - was a bit tied up in the run up to christmas. Right now i'd be the only maintainer (something i'd like to address going forward). I've followed you on twitter - i have the same handle there - or i'm on Keybase with the same handle too. Maintainer lists on pypi are public, so my pypi handle is [johncarr](https://pypi.org/user/johncarr/).

**Comment by Jc2k** [comment]
@d1str0 any chance of getting [johncarr](https://pypi.org/user/johncarr/) added to the hpfeeds pypi project so I can push out a new release?

**Comment by Jc2k** [comment]
@d1str0 Any update? Would be great to pull the python broker out of this module into a seperate package, but a bit of a pain to do until i can start doing pypi releases.

**Comment by d1str0** [comment]
Do you have 2FA enabled on pypi.org? If not, please do so.

**Comment by Jc2k** [comment]
Of course!

Thanks very much for sorting this out. I'll probably push out a release as is this week, and bump the major version to make it clear something has happened.

It looks like you are still the owner on pypi? - I hope that means you plan to become a contributor to the python hpfeeds client :-) If not at some point down the line we should probably have a chat. Short term it makes sense that you would not turn the package over to an unknown entity, but long term I think it makes sense for the hpfeeds pypi project to belong to the people doing releases. So at least thats what I want to work towards.

**Comment by d1str0** [comment]
Yes, we will see. I don't plan on contributing to hpfeeds but my project does rely on it. Once I move my project off of a python implementation I will gladly move over ownership.

**Comment by kevthehermit** [comment]
Any movement on this?

**Comment by Jc2k** [comment]
@kevthehermit hoped to do it yesterday but ran out of time. Hopefully Monday...

**Comment by Jc2k** [comment]
This was done a while ago, so closing.
